version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.name=node1
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- esdata1:/usr/share/elasticsearch/data
      - type: bind
        source: //f/docker.data/node1
        target: /usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      - node.name=node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      #- esdata2:/usr/share/elasticsearch/data
      - type: bind
        source: //f/docker.data/node2
        target: /usr/share/elasticsearch/data
    ports:
      - 9201:9200
    networks:
      - esnet
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    container_name: kibana
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
    networks:
      - esnet
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

# volumes:
#   esdata1:
#     driver: local
#   esdata2:
#     driver: local

networks:
  esnet: